import type { InventoryItem } from "@/types/inventory"
import type { Recipe } from "@/types/recipe"

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "1",
    name: "Milk",
    category: "dairy",
    quantity: 1,
    purchaseDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    expirationDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    daysUntilExpiration: 2,
    totalShelfLife: 14,
  },
  {
    id: "2",
    name: "Spinach",
    category: "vegetables",
    quantity: 1,
    purchaseDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    expirationDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days from now
    daysUntilExpiration: 3,
    totalShelfLife: 7,
  },
  {
    id: "3",
    name: "Chicken Breast",
    category: "poultry",
    quantity: 2,
    purchaseDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    expirationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // 1 day from now
    daysUntilExpiration: 1,
    totalShelfLife: 5,
  },
  {
    id: "4",
    name: "Eggs",
    category: "dairy",
    quantity: 12,
    purchaseDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    expirationDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // 10 days from now
    daysUntilExpiration: 10,
    totalShelfLife: 21,
  },
  {
    id: "5",
    name: "Tomatoes",
    category: "vegetables",
    quantity: 4,
    purchaseDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    expirationDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000), // 4 days from now
    daysUntilExpiration: 4,
    totalShelfLife: 7,
  },
]

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    name: "Chicken and Spinach Salad",
    cuisineType: "Healthy",
    prepTime: 15,
    usesIngredients: ["Chicken Breast", "Spinach", "Tomatoes"],
    instructions: [
      "Chop the chicken breast into bite-sized pieces and cook until no longer pink.",
      "Wash and dry the spinach leaves.",
      "Slice the tomatoes into wedges.",
      "Combine all ingredients in a large bowl.",
      "Drizzle with your favorite dressing and serve.",
    ],
    dietaryTags: ["high-protein", "low-carb"],
    ingredients: [
      "2 cups cooked Chicken Breast, diced",
      "4 cups fresh Spinach leaves",
      "2 medium Tomatoes, sliced",
      "2 tablespoons olive oil",
      "1 tablespoon balsamic vinegar",
      "Salt and pepper to taste",
    ],
  },
  {
    id: "2",
    name: "Spinach and Egg Frittata",
    cuisineType: "Italian",
    prepTime: 25,
    usesIngredients: ["Eggs", "Spinach", "Milk"],
    instructions: [
      "Preheat oven to 350°F (175°C).",
      "Whisk eggs and milk together in a bowl.",
      "Sauté spinach until wilted.",
      "Pour egg mixture over spinach in an oven-safe skillet.",
      "Bake for 15-20 minutes until set.",
    ],
    dietaryTags: ["vegetarian", "gluten-free"],
    ingredients: [
      "8 large Eggs",
      "1/4 cup Milk",
      "2 cups fresh Spinach",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
      "1/4 cup grated Parmesan cheese (optional)",
    ],
  },
  {
    id: "3",
    name: "Tomato and Egg Breakfast Scramble",
    cuisineType: "American",
    prepTime: 10,
    usesIngredients: ["Eggs", "Tomatoes"],
    instructions: [
      "Dice tomatoes into small pieces.",
      "Beat eggs in a bowl.",
      "Heat a non-stick pan over medium heat.",
      "Add eggs and tomatoes, stirring frequently until eggs are cooked.",
      "Season with salt and pepper to taste.",
    ],
    dietaryTags: ["vegetarian", "quick", "high-protein"],
    ingredients: ["4 large Eggs", "2 medium Tomatoes, diced", "1 tablespoon butter", "Salt and pepper to taste"],
  },
  {
    id: "4",
    name: "Scrambled Eggs",
    cuisineType: "American",
    prepTime: 10,
    usesIngredients: ["Eggs", "Milk"],
    instructions: [
      "Prep Veggies/Add-ins: If using, sauté diced onions, bell peppers, or mushrooms in a pan with a tiny bit of butter or oil until softened (2-3 minutes). Add spinach or tomatoes at the very end until just wilted. Remove from pan and set aside.",
      "Whisk Eggs: In a bowl, whisk eggs with milk (if using), salt, and pepper until well combined and slightly frothy.",
      "Cook: Melt butter in a non-stick skillet over medium-low heat. Pour in the egg mixture.",
      "Scramble: As the eggs set, gently push cooked portions from the edges to the center with a spatula, tilting the pan to allow uncooked egg to flow underneath.",
      "Add-ins: When eggs are mostly set but still slightly moist, stir in your pre-cooked vegetables, cheese, or herbs. Cook for another 30 seconds to a minute, until eggs are cooked to your desired consistency and cheese is melted.",
      "Serve immediately.",
    ],
    dietaryTags: ["vegetarian", "quick", "high-protein"],
    ingredients: [
      "2-3 large Eggs per person",
      "1-2 tablespoons Milk or cream (optional, for fluffiness)",
      "1 teaspoon Butter or oil",
      "Salt and Black Pepper to taste",
      "Optional Add-ins: 1/4 cup finely diced Onion or Shallot",
      "1/4 cup diced Bell Pepper (any color)",
      "1/2 cup fresh Spinach or other leafy greens",
      "2-3 sliced Mushrooms",
      "1/4 cup diced Tomato",
      "2 tablespoons shredded Cheese (Cheddar, Monterey Jack, Swiss)",
      "1 tablespoon chopped fresh Herbs (chives, parsley, dill, cilantro)",
      "Cooked ham, bacon, or sausage bits (leftovers)",
    ],
  },
  {
    id: "5",
    name: "Pasta with Tomato Sauce",
    cuisineType: "Italian",
    prepTime: 30,
    usesIngredients: ["Tomatoes", "Onion"],
    instructions: [
      "Cook Pasta: Bring a large pot of salted water to a boil. Add pasta and cook according to package directions until al dente. Drain, reserving about 1/2 cup of pasta water.",
      "Sauté Aromatics: While pasta cooks, heat olive oil in a large skillet or pot over medium heat. Add chopped onion and sauté until softened and translucent, about 5-7 minutes. Add minced garlic and optional diced bell pepper/carrot/zucchini, cook for another 2-3 minutes until fragrant.",
      "Simmer Sauce: Stir in crushed tomatoes (and any other tomato products you're using), vegetable broth/water/wine, dried oregano, salt, pepper, and an optional pinch of sugar. If using cooked ground meat, stir it in now. Bring to a gentle simmer.",
      "Finish Sauce: Reduce heat to low, cover, and simmer for at least 15-20 minutes, or longer if you have time, stirring occasionally. The longer it simmers, the more the flavors meld. If the sauce becomes too thick, add a splash of the reserved pasta water.",
      "Combine: Stir in fresh basil (if using) just before serving. Add the drained pasta directly to the sauce and toss to coat.",
      "Serve immediately, topped with Parmesan cheese if desired.",
    ],
    dietaryTags: ["vegetarian"],
    ingredients: [
      "8 oz (about half a box) dry Pasta (spaghetti, penne, rotini)",
      "1 tablespoon Olive Oil",
      "1 medium Onion, finely chopped",
      "2-3 cloves Garlic, minced",
      "1 (28 oz) can crushed Tomatoes or 1 (14.5 oz) can diced Tomatoes + 1/2 (15 oz) can Tomato Sauce",
      "1/2 cup Vegetable Broth or Water (or leftover Red Wine)",
      "1 teaspoon dried Oregano or 1 tablespoon fresh Oregano (chopped)",
      "1/4 cup chopped fresh Basil (if available)",
      "Salt and Black Pepper to taste",
      "Pinch of sugar (optional, to balance acidity)",
      "Optional Add-ins: 1/2 Bell Pepper, finely diced",
      "1/2 Zucchini, grated or finely diced",
      "1 Carrot, finely grated",
      "Any cooked Ground Meat (beef, turkey, sausage)",
      "Parmesan Cheese for serving",
    ],
  },
  {
    id: "6",
    name: "Tuna Sandwich",
    cuisineType: "American",
    prepTime: 10,
    usesIngredients: ["Celery", "Onion"],
    instructions: [
      "Mix Tuna Salad: In a medium bowl, flake the drained tuna with a fork.",
      "Add mayonnaise, diced celery, diced onion, relish, Dijon mustard (if using), and lemon juice (if using).",
      "Season with salt and black pepper. Stir until all ingredients are well combined. Taste and adjust seasonings as needed.",
      "Assemble Sandwich: Lay out two slices of bread. Spread the tuna salad mixture evenly over one slice.",
      "Top with optional lettuce, tomato, or cheese if using.",
      "Place the second slice of bread on top.",
      "Serve immediately.",
    ],
    dietaryTags: ["high-protein", "quick"],
    ingredients: [
      "1 (5 oz) can Tuna in water or oil, drained",
      "2 tablespoons Mayonnaise (or more, to taste)",
      "1 stalk Celery, finely diced",
      "2 tablespoons finely diced Red Onion or Green Onion (scallion)",
      "1 tablespoon Sweet Pickle Relish or chopped Dill Pickles",
      "1 teaspoon Dijon Mustard (optional, for tang)",
      "Squeeze of fresh Lemon Juice (optional)",
      "Salt and Black Pepper to taste",
      "2 slices Bread (any kind: white, whole wheat, sourdough) per sandwich",
      "Optional Toppings: Lettuce leaves, Tomato slices, Cheese slice",
    ],
  },
  {
    id: "7",
    name: "Bean Tacos",
    cuisineType: "Mexican",
    prepTime: 20,
    usesIngredients: ["Onion", "Bell Pepper"],
    instructions: [
      "Prep Beans: Heat olive oil in a skillet over medium heat. Add diced onion and bell pepper (if using) and sauté until softened, about 5 minutes. Add minced garlic, chili powder, cumin, and cayenne (if using), and cook for 1 minute until fragrant.",
      "Stir in the rinsed and drained black beans. Add vegetable broth or water.",
      "Bring to a simmer, then reduce heat to low and mash about half of the beans with a fork or potato masher directly in the pan. This creates a creamier texture while still leaving some whole beans. Simmer for 5-7 minutes, allowing flavors to meld and liquid to reduce. Season with salt and pepper to taste.",
      "Warm Tortillas: While beans simmer, warm tortillas in a dry skillet over medium-high heat for 30 seconds per side, in the microwave (stack and wrap in damp paper towel for 30-60 seconds), or in the oven.",
      "Assemble Tacos: Spoon the warm bean mixture into the warmed tortillas.",
      "Add Toppings: Top with your desired ingredients like avocado, cilantro, salsa, cheese, sour cream/yogurt, and a squeeze of fresh lime juice.",
    ],
    dietaryTags: ["vegetarian", "vegan", "high-fiber"],
    ingredients: [
      "8-12 small Corn or Flour Tortillas",
      "1 tablespoon Olive Oil",
      "1/2 medium Onion, diced",
      "2-3 cloves Garlic, minced",
      "1 (15 oz) can Black Beans (or pinto beans), rinsed and drained",
      "1 teaspoon Chili Powder",
      "1/2 teaspoon Cumin",
      "Pinch of Cayenne Pepper (optional, for heat)",
      "1/4 cup Vegetable Broth or Water",
      "Salt and Black Pepper to taste",
      "Optional Toppings: 1/2 Bell Pepper, diced",
      "1/2 Avocado, diced or mashed",
      "1/4 cup chopped fresh Cilantro",
      "Salsa, Shredded Cheese, Sour Cream or plain Yogurt",
      "Lime wedges",
    ],
  },
  {
    id: "8",
    name: "Stir-Fried Rice",
    cuisineType: "Asian",
    prepTime: 15,
    usesIngredients: ["Eggs", "Carrots", "Onion"],
    instructions: [
      "Prep: Ensure your cooked rice is cold and ideally day-old (this prevents it from clumping). Chop all your vegetables and mince garlic and ginger.",
      "Cook Eggs (Optional): If using eggs, heat 1 teaspoon of oil in a large skillet or wok over medium-high heat. Pour in beaten eggs and scramble quickly. Remove from pan and set aside.",
      "Sauté Aromatics & Veggies: Add remaining oil to the same skillet/wok over medium-high heat. Add diced onion, carrots, and any harder vegetables (like broccoli florets or bell peppers) first. Stir-fry for 2-3 minutes until slightly tender-crisp.",
      "Add minced garlic and ginger (if using). Stir-fry for another 1 minute until fragrant.",
      "Add Rice: Add the cold cooked rice to the skillet. Break up any clumps with your spatula. Stir-fry for 3-5 minutes, pressing the rice against the pan to get some browning, until heated through.",
      "Add Remaining Veggies & Sauce: Stir in softer vegetables like frozen peas, corn, or mushrooms. Pour soy sauce evenly over the rice. Continue to stir-fry for 2-3 minutes, ensuring all ingredients are well combined and the rice absorbs the soy sauce.",
      "Finish: Stir in the cooked scrambled egg (if using). Remove from heat and drizzle with sesame oil (if using). Taste and adjust seasoning with more soy sauce, salt, or pepper if needed.",
      "Garnish with sliced green onions before serving.",
    ],
    dietaryTags: ["vegetarian", "quick", "customizable"],
    ingredients: [
      "3 cups cold, day-old Cooked Rice (essential for best texture)",
      "1-2 tablespoons Vegetable Oil (or sesame oil for flavor)",
      "1/2 cup diced Onion",
      "2-3 cloves Garlic, minced",
      "1 tablespoon fresh Ginger, grated or minced (optional)",
      "1-2 Eggs, lightly beaten (optional)",
      "1.5 - 2 cups Mixed Vegetables: Diced Carrots, Frozen Peas, Frozen Corn, Diced Bell Pepper, Small Broccoli florets, Sliced Mushrooms, Shredded Cabbage, Thinly sliced Green Beans",
      "2-3 tablespoons Soy Sauce (to taste)",
      "1 teaspoon Sesame Oil (for finishing, optional)",
      "Salt and Black Pepper to taste",
      "2 Green Onions (Scallions), sliced (for garnish)",
    ],
  },
]
