# Generated by Django 5.2.4 on 2025-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
